# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://timeseriesAI.github.io/timeseries/"

git_url = "https://github.com/timeseriesAI/timeseries/tree/master/"

def custom_doc_links(name): return None
