# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/000_utils.ipynb (unless otherwise specified).

__all__ = ['ToTensor', 'ToArray', 'To3DTensor', 'To2DTensor', 'To1DTensor', 'To3DArray', 'To2DArray', 'To1DArray',
           'To3D', 'To2D', 'To1D', 'To2DPlus', 'To3DPlus', 'To2DPlusTensor', 'To2DPlusArray', 'To3DPlusTensor',
           'To3DPlusArray', 'ToType', 'bytes2size', 'bytes2GB', 'delete_all_in_dir', 'reverse_dict', 'is_tuple',
           'itemify', 'ifnotnone', 'ifnoneelse']

# Cell
from .imports import *

# Cell
def ToTensor(o):
    if isinstance(o, np.ndarray):  return torch.from_numpy(o)
    if not isinstance(o, torch.Tensor): print(f"Can't convert {type(o)} to torch.Tensor")
    return o


def ToArray(o):
    if isinstance(o, torch.Tensor): o = o.cpu().numpy()
    elif not isinstance(o, np.ndarray): print(f"Can't convert {type(o)} to np.array")
    return o


def To3DTensor(o):
    o = ToTensor(o)
    if o.ndim == 1: o = o[None, None]
    elif o.ndim == 2: o = o[:, None]
    assert o.ndim == 3, f'Please, review input dimensions {o.ndim}'
    return o


def To2DTensor(o):
    o = ToTensor(o)
    if o.ndim == 1: o = o[None]
    elif o.ndim == 3: o = torch.squeeze(o, 0)
    assert o.ndim == 2, f'Please, review input dimensions {o.ndim}'
    return o


def To1DTensor(o):
    o = ToTensor(o)
    if o.ndim == 3: o = torch.squeeze(o, 1)
    if o.ndim == 2: o = torch.squeeze(o, 0)
    assert o.ndim == 1, f'Please, review input dimensions {o.ndim}'
    return o


def To3DArray(o):
    o = ToArray(o)
    if o.ndim == 1: o = o[None, None]
    elif o.ndim == 2: o = o[:, None]
    elif o.ndim == 4: o = o[0]
    assert o.ndim == 3, f'Please, review input dimensions {o.ndim}'
    return o


def To2DArray(o):
    o = ToArray(o)
    if o.ndim == 1: o = o[None]
    if o.ndim == 3: o = np.squeeze(o, 0)
    assert o.ndim == 2, f'Please, review input dimensions {o.ndim}'
    return o


def To1DArray(o):
    o = ToArray(o)
    if o.ndim == 3: o = np.squeeze(o, 1)
    if o.ndim == 2: o = np.squeeze(o, 0)
    assert o.ndim == 1, f'Please, review input dimensions {o.ndim}'
    return o


def To3D(o):
    if isinstance(o, np.ndarray): return To3DArray(o)
    if isinstance(o, torch.Tensor): return To3DTensor(o)


def To2D(o):
    if isinstance(o, np.ndarray): return To2DArray(o)
    if isinstance(o, torch.Tensor): return To2DTensor(o)


def To1D(o):
    if isinstance(o, np.ndarray): return To1DArray(o)
    if isinstance(o, torch.Tensor): return To1DTensor(o)


def To2DPlus(o):
    if o.ndim >= 2: return o
    if isinstance(o, np.ndarray): return To2DArray(o)
    elif isinstance(o, torch.Tensor): return To2DTensor(o)


def To3DPlus(o):
    if o.ndim >= 3: return o
    if isinstance(o, np.ndarray): return To3DArray(o)
    elif isinstance(o, torch.Tensor): return To3DTensor(o)


def To2DPlusTensor(o):
    return To2DPlus(ToTensor(o))


def To2DPlusArray(o):
    return To2DPlus(ToArray(o))


def To3DPlusTensor(o):
    return To3DPlus(ToTensor(o))


def To3DPlusArray(o):
    return To3DPlus(ToArray(o))


def ToType(dtype):
    def _to_type(o, dtype=dtype):
        if isinstance(o, np.ndarray) and o.dtype != dtype: o = o.astype(dtype)
        elif isinstance(o, torch.Tensor) and o.dtype != dtype: o = o.to(dtype=dtype)
        return o
    return _to_type

# Cell
import math
def bytes2size(size_bytes):
    if size_bytes == 0: return "0B"
    size_name = ("B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB")
    i = int(math.floor(math.log(size_bytes, 1024)))
    p = math.pow(1024, i)
    s = round(size_bytes / p, 2)
    return "%s %s" % (s, size_name[i])

def bytes2GB(bytes):
    return round(bytes / math.pow(1024, 3), 2)

# Cell
def delete_all_in_dir(tgt_dir:str, exception:Union[str, tuple]=None):
    if exception is not None and len(L(exception)) > 1: exception = tuple(exception)
    for file in os.listdir(tgt_dir):
        if exception is not None and file.endswith(exception): continue
        file_path = os.path.join(tgt_dir, file)
        if os.path.isfile(file_path) or os.path.islink(file_path): os.unlink(file_path)
        elif os.path.isdir(file_path): shutil.rmtree(file_path)

# Cell
def reverse_dict(dictionary):
    return {v: k for k, v in dictionary.items()}

# Cell
def is_tuple(o): return isinstance(o, tuple)

# Cell
def itemify(*o): return L(*o).zip()

# Cell
def ifnotnone(a, b):
    "`a` if `a` is None else `b`"
    return a if a is None else b

# Cell
def ifnoneelse(a, b, c):
    "`b` if `a` is None else `c`"
    return b if a is None else c